eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

